// Shared client helpers: image compression for uploads, printable receipts
// and CSV export.

export const rupeeFmt = (n) => '₹' + (Number(n) || 0).toLocaleString('en-IN');

// Read a File and return a resized JPEG data-URL (keeps uploads small enough
// for the JSON body limit; ID cards stay perfectly readable at 1100px).
export function fileToDataUrl(file, maxSide = 1100, quality = 0.82) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error('Could not read the file'));
    reader.onload = () => {
      const img = new Image();
      img.onerror = () => reject(new Error('Not a valid image'));
      img.onload = () => {
        const scale = Math.min(1, maxSide / Math.max(img.width, img.height));
        const canvas = document.createElement('canvas');
        canvas.width = Math.round(img.width * scale);
        canvas.height = Math.round(img.height * scale);
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
        resolve(canvas.toDataURL('image/jpeg', quality));
      };
      img.src = reader.result;
    };
    reader.readAsDataURL(file);
  });
}

export function downloadCsv(filename, rows) {
  const csv = rows.map(r => r.map(v => `"${String(v ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob(['﻿' + csv], { type: 'text/csv' }));
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

// Open a print-ready window (user can print or "Save as PDF" from the dialog).
export function printHtml(title, bodyHtml) {
  const w = window.open('', '_blank', 'width=430,height=640');
  if (!w) { alert('Allow pop-ups to print'); return; }
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
  <style>
    body { font-family: 'Segoe UI', system-ui, sans-serif; color:#1c2136; margin:0; padding:24px; }
    .rc { max-width:380px; margin:0 auto; border:1px solid #d8dcf0; border-radius:14px; overflow:hidden; }
    .rc-head { background:#6c5ce7; color:#fff; padding:16px 20px; }
    .rc-head h2 { margin:0; font-size:18px; } .rc-head .sub { opacity:.85; font-size:12px; margin-top:2px; }
    .rc-body { padding:16px 20px; }
    table { width:100%; border-collapse:collapse; font-size:13px; }
    td { padding:6px 0; vertical-align:top; } td:last-child { text-align:right; font-weight:600; }
    tr.line td { border-top:1px dashed #d8dcf0; }
    .amt { font-size:26px; font-weight:800; }
    .tag { display:inline-block; padding:3px 10px; border-radius:99px; font-size:12px; font-weight:700; }
    .tag.paid { background:#e3f8f0; color:#0c8f6c; } .tag.pending { background:#fdeceb; color:#c53030; }
    .foot { text-align:center; font-size:11px; color:#6a7188; padding:12px; border-top:1px solid #eee; }
    @media print { body { padding:0 } }
  </style></head><body>${bodyHtml}
  <script>window.onload = () => setTimeout(() => window.print(), 250);<\/script></body></html>`);
  w.document.close();
}

export function receiptHtml({ receiptNo, tenantName, propertyName, roomName, phone, amount, mode, date, type, balanceAfter, clearedOldDues }) {
  const pending = Number(balanceAfter) > 0;
  return `<div class="rc">
    <div class="rc-head"><h2>🏠 StaySathi — ${type === 'advance' ? 'Advance' : 'Rent'} Receipt</h2>
      <div class="sub">${propertyName || ''}${roomName ? ' · Room ' + roomName : ''}</div></div>
    <div class="rc-body">
      <table>
        <tr><td>Receipt No.</td><td>${receiptNo || '-'}</td></tr>
        <tr><td>Date</td><td>${date || ''}</td></tr>
        <tr><td>Received from</td><td>${tenantName || ''}${phone ? '<br><span style="font-weight:400;color:#6a7188">' + phone + '</span>' : ''}</td></tr>
        <tr><td>Payment mode</td><td>${String(mode || 'cash').toUpperCase()}</td></tr>
        <tr class="line"><td>Amount received</td><td class="amt">${rupeeFmt(amount)}</td></tr>
        ${clearedOldDues > 0 ? `<tr><td>Adjusted to old dues</td><td>${rupeeFmt(clearedOldDues)}</td></tr>` : ''}
        ${type !== 'advance' && balanceAfter !== undefined ? `<tr class="line"><td>Balance after payment</td>
          <td><span class="tag ${pending ? 'pending' : 'paid'}">${pending ? 'PENDING ' + rupeeFmt(balanceAfter) : 'ALL CLEAR ✓'}</span></td></tr>` : ''}
      </table>
    </div>
    <div class="foot">Generated by StaySathi · This is a computer generated receipt</div>
  </div>`;
}
