import React, { useCallback, useEffect, useState } from 'react';
import { get, post, del } from '../api.js';
import { useLang } from '../i18n.jsx';
import { Modal, Field, Empty, rupee } from '../components/ui.jsx';
import TenantSheet from '../components/TenantSheet.jsx';
import { downloadCsv, printHtml, receiptHtml } from '../util.js';
import { RupeeCount } from '../fx.jsx';
import { useToast } from '../App.jsx';

const EXPENSE_CATS = [
  ['electricity', '⚡'], ['water', '💧'], ['groceries', '🛒'],
  ['maintenance', '🔧'], ['wifi', '📶'], ['salary', '👛'], ['other', '📦']
];

// chart colors validated against the white card surface (green↔red sits in
// the CVD floor band, so every chart also carries a legend + direct labels)
const C_PAID = '#0c8f6c', C_PENDING = '#e5484d', C_ACCENT = '#6c5ce7';

export default function Money({ overview, refreshOverview, initialSeg }) {
  const { t } = useLang();
  const toast = useToast();
  const [seg, setSeg] = useState(initialSeg || 'dues'); // dues | payments | expenses | report
  const [propId, setPropId] = useState('');
  const [dues, setDues] = useState(null);
  const [payments, setPayments] = useState(null);
  const [expenses, setExpenses] = useState(null);
  const [report, setReport] = useState(null);
  const [modal, setModal] = useState(null);
  const [sheetTenant, setSheetTenant] = useState(null);

  const q = propId ? `?propertyId=${propId}` : '';
  const load = useCallback(() => {
    get(`/dues${q}`).then(d => setDues(d.dues)).catch(() => {});
    get(`/payments${q}`).then(d => setPayments(d.payments)).catch(() => {});
    get(`/expenses${q}`).then(d => setExpenses(d.expenses)).catch(() => {});
    get(`/reports${q}`).then(setReport).catch(() => {});
  }, [q]);
  useEffect(() => { load(); }, [load]);

  const totals = overview?.totals;
  const properties = overview?.properties || [];

  const openTenant = (row) => {
    setSheetTenant({ ...row.tenant, dues: row.dues, propertyName: row.propertyName, roomName: row.roomName });
  };

  const collected = propId ? properties.find(p => p.id === propId)?.stats.collectedThisMonth : totals?.collectedThisMonth;
  const totalDue = dues?.reduce((a, d) => a + d.dues.dueAmount, 0) || 0;
  const rate = (collected || 0) + totalDue > 0 ? Math.round((collected || 0) / ((collected || 0) + totalDue) * 100) : 100;

  const thisMonthExp = (expenses || []).filter(e => (e.date || '').startsWith(new Date().toISOString().slice(0, 7)))
    .reduce((a, e) => a + Number(e.amount), 0);

  const exportPayments = () => downloadCsv('staysathi-payments.csv', [
    ['Date', 'Tenant', 'Amount', 'Type', 'Mode', 'Balance After', 'Receipt'],
    ...(payments || []).map(p => [p.date, p.tenantName, p.amount, p.type || 'rent', p.mode, p.balanceAfter ?? '', p.receiptNo])
  ]);
  const exportExpenses = () => downloadCsv('staysathi-expenses.csv', [
    ['Date', 'Category', 'Amount', 'Note'],
    ...(expenses || []).map(e => [e.date, e.category, e.amount, e.note])
  ]);
  const printPayment = (p) => {
    const propName = properties.find(x => x.id === p.propertyId)?.name || '';
    printHtml(`Receipt ${p.receiptNo}`, receiptHtml({ ...p, propertyName: propName }));
  };
  const printReport = () => {
    if (!report) return;
    const rows = (dues || []).map(r =>
      `<tr><td>${r.tenant.name}</td><td>${r.propertyName || ''} · ${r.roomName || ''}</td><td style="text-align:right">${rupee(r.dues.previousDue)}</td><td style="text-align:right">${rupee(r.dues.currentDue)}</td><td style="text-align:right;font-weight:700">${rupee(r.dues.dueAmount)}</td></tr>`).join('');
    printHtml('StaySathi Report', `<div class="rc"><div class="rc-head"><h2>📊 StaySathi — Monthly Report</h2>
      <div class="sub">${new Date().toLocaleDateString()}</div></div><div class="rc-body">
      <table><tr><td>${t('collected')} (${t('thisMonth')})</td><td>${rupee(collected)}</td></tr>
      <tr><td>${t('totalPendingDues')}</td><td>${rupee(totalDue)}</td></tr>
      <tr><td>${t('occupancyRate')}</td><td>${report.occupancy?.occupied}/${report.occupancy?.beds} (${report.occupancy?.rate}%)</td></tr>
      <tr><td>${t('collectionRate')}</td><td>${rate}%</td></tr></table>
      <h3 style="margin:14px 0 6px;font-size:14px">⚠️ ${t('duesTitle')}</h3>
      <table><tr style="color:#6a7188;font-size:11px"><td>Tenant</td><td>Where</td><td style="text-align:right">Old</td><td style="text-align:right">Month</td><td style="text-align:right">Total</td></tr>${rows}</table>
      </div><div class="foot">Generated by StaySathi</div></div>`);
  };

  return (
    <div className="page">
      <h2 className="title">💰 {t('navMoney')}</h2>

      <div className="filter-bar">
        <select className="input" value={propId} onChange={e => setPropId(e.target.value)}>
          <option value="">🏠 {t('allProperties')}</option>
          {properties.map(p => <option key={p.id} value={p.id}>{p.icon} {p.name}</option>)}
        </select>
      </div>

      <div className="money-hero mt16">
        <div className="money-tile gain tap" onClick={() => setSeg('payments')}>
          <div className="muted small">✅ {t('collected')} · {t('thisMonth')}</div>
          <div className="amt"><RupeeCount value={collected || 0} /></div>
        </div>
        <div className="money-tile loss tap" onClick={() => setSeg('dues')}>
          <div className="muted small">⚠️ {t('duesTitle')}</div>
          <div className="amt"><RupeeCount value={totalDue} /></div>
        </div>
      </div>

      <div className="seg mt16">
        {[['dues', `⚠️ ${t('duesTitle')}`], ['payments', `🧾 ${t('recentPayments')}`], ['expenses', `🛒 ${t('expenses')}`], ['report', `📊 ${t('analytics')}`]].map(([v, l]) => (
          <button key={v} className={seg === v ? 'active' : ''} onClick={() => setSeg(v)}>{l}</button>
        ))}
      </div>

      {/* -------- dues: every row opens the tenant directly -------- */}
      {seg === 'dues' && (
        <div className="mt16">
          {dues && dues.length > 0 && <p className="muted small mb16">👆 {t('tapToCollect')} · ℹ️ {t('clearsOldFirst')}</p>}
          {dues && dues.length === 0 && <Empty icon="🎉" text={t('noDues')} />}
          {(dues || []).map(row => (
            <div key={row.tenant.id} className="list-item tap" onClick={() => openTenant(row)}>
              <div className="avatar">{row.tenant.name[0]}</div>
              <div className="grow">
                <b>{row.tenant.name}</b>
                <div className="muted small">{row.propertyName} · {t('room')} {row.roomName}</div>
                <div className="row wrap mt8">
                  {row.dues.previousDue > 0 && <span className="chip red small">⏮️ {t('previousDues')}: {rupee(row.dues.previousDue)}</span>}
                  {row.dues.currentDue > 0 && <span className="chip orange small">📅 {t('currentMonth')}: {rupee(row.dues.currentDue)}</span>}
                </div>
              </div>
              <div className="center">
                <div className="due-amt">{rupee(row.dues.dueAmount)}</div>
                <button className="btn btn-sm btn-green mt8" onClick={(e) => { e.stopPropagation(); openTenant(row); }}>💰 {t('collect')}</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* -------- payments -------- */}
      {seg === 'payments' && (
        <div className="mt16">
          <div className="row spread mb16">
            <span className="chip green">🧾 {(payments || []).length}</span>
            <button className="btn btn-sm" onClick={exportPayments}>⬇️ {t('exportCsv')}</button>
          </div>
          {payments && payments.length === 0 && <Empty icon="🧾" text={t('noPaymentsRecorded')} />}
          {(payments || []).map(p => (
            <div key={p.id} className="list-item">
              <div className="avatar" style={{ background: p.type === 'advance' ? 'linear-gradient(135deg,#0984e3,#74b9ff)' : 'linear-gradient(135deg,#0ea97f,#2fd3a5)' }}>{p.type === 'advance' ? '🏦' : '₹'}</div>
              <div className="grow">
                <b>{p.tenantName}{p.type === 'advance' ? ` · ${t('advance')}` : ''}</b>
                <div className="muted small">{p.date} · {p.mode.toUpperCase()} · {t('receipt')} {p.receiptNo}</div>
                {p.balanceAfter > 0 && <span className="chip red small mt8">⚠️ {t('stillPending')}: {rupee(p.balanceAfter)}</span>}
              </div>
              <div className="center">
                <b style={{ color: 'var(--green2)' }}>{rupee(p.amount)}</b>
                <div className="row mt8">
                  <button className="btn btn-sm btn-ghost" title={t('printReceipt')} onClick={() => printPayment(p)}>🖨️</button>
                  <button className="btn btn-sm btn-ghost" title={t('shareReceipt')} onClick={() => {
                    const text = `🧾 ${t('receipt')} ${p.receiptNo}\n${p.tenantName}\n${t('amount')}: ₹${p.amount}\n${t('date')}: ${p.date} · ${p.mode.toUpperCase()}${p.balanceAfter > 0 ? `\n${t('stillPending')}: ₹${p.balanceAfter}` : ''}\n— StaySathi`;
                    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
                  }}>📤</button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* -------- expenses -------- */}
      {seg === 'expenses' && (
        <div className="mt16">
          <div className="row spread mb16">
            <span className="chip orange">🛒 {t('thisMonth')}: {rupee(thisMonthExp)}</span>
            <div className="row">
              <button className="btn btn-sm" onClick={exportExpenses}>⬇️ {t('exportCsv')}</button>
              <button className="btn btn-sm btn-primary" onClick={() => setModal('addExpense')}>➕ {t('addExpense')}</button>
            </div>
          </div>
          {expenses && expenses.length === 0 && <Empty icon="🛒" text={t('noExpensesYet')} />}
          {(expenses || []).map(e => {
            const ico = EXPENSE_CATS.find(c => c[0] === e.category)?.[1] || '📦';
            return (
              <div key={e.id} className="list-item">
                <div className="avatar" style={{ background: 'linear-gradient(135deg,#f59f00,#ffc14d)' }}>{ico}</div>
                <div className="grow">
                  <b>{t(e.category)}</b>
                  <div className="muted small">{e.date}{e.note ? ` · ${e.note}` : ''}</div>
                </div>
                <div className="row">
                  <b>{rupee(e.amount)}</b>
                  <button className="btn btn-sm btn-ghost" onClick={async () => { if (window.confirm(t('deleteQ'))) { await del(`/expenses/${e.id}`); load(); refreshOverview(); } }}>🗑️</button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* -------- analytics -------- */}
      {seg === 'report' && report && (
        <>
          <div className="row spread mt16">
            <span />
            <button className="btn btn-sm" onClick={printReport}>🖨️ {t('printReceipt')}</button>
          </div>

          {/* KPI row */}
          <div className="stat-strip mt8">
            <div className="stat-tile"><div className="v">🛏️ {report.occupancy?.occupied}/{report.occupancy?.beds}</div><div className="k">{t('occupancyRate')} · {report.occupancy?.rate}%</div></div>
            <div className="stat-tile"><div className="v" style={{ color: C_PAID }}>{rupee(collected)}</div><div className="k">{t('collected')}</div></div>
            <div className="stat-tile"><div className="v" style={{ color: totalDue ? '#c53030' : C_PAID }}>{rupee(totalDue)}</div><div className="k">{t('totalPendingDues')}</div></div>
            <div className="stat-tile"><div className="v">🧑 {propId ? properties.find(p => p.id === propId)?.stats.tenants : totals?.tenants}</div><div className="k">{t('activeTenants')}</div></div>
          </div>

          {/* occupancy meter + collection rate */}
          <div className="card mt16">
            <div className="row" style={{ alignItems: 'center', gap: 18 }}>
              <OccupancyRing rate={report.occupancy?.rate || 0} />
              <div className="grow">
                <b>🛏️ {t('occupancyRate')}</b>
                <div className="row spread mt8 small"><span className="muted">{t('occupied')}</span><b>{report.occupancy?.occupied}</b></div>
                <div className="row spread small"><span className="muted">{t('vacant')}</span><b>{report.occupancy?.vacant}</b></div>
                <div className="row spread mt8"><span className="muted small">🎯 {t('collectionRate')}</span>
                  <b style={{ color: rate >= 80 ? C_PAID : rate >= 50 ? 'var(--gold)' : '#c53030' }}>{rate}%</b></div>
                <div className="progress mt8"><div style={{ width: `${rate}%` }} /></div>
              </div>
            </div>
          </div>

          {/* rent collection: paid vs pending by month */}
          {report.rentSeries && (
            <div className="card mt16">
              <b>💰 {t('rentCollection')}</b>
              <PairBars series={report.rentSeries} />
              <div className="row wrap mt8">
                <span className="chip" style={{ color: C_PAID }}>■ {t('collectedLabel')}</span>
                <span className="chip" style={{ color: C_PENDING }}>■ {t('pendingLabel')}</span>
              </div>
            </div>
          )}

          {/* revenue trend */}
          {report.revenue && (
            <div className="card mt16">
              <b>📈 {t('revenueTrend')} · 12 {t('months')}</b>
              <AreaChart series={report.revenue} />
            </div>
          )}

          {/* floor-wise */}
          {report.floors?.length > 0 && (
            <div className="card mt16">
              <b>🪜 {t('floorWise')}</b>
              {report.floors.map(f => (
                <div key={f.id} className="mt16">
                  <div className="row spread small">
                    <b>{f.name}{!propId && f.propertyName ? ` · ${f.propertyName}` : ''}</b>
                    <span className="muted">🛏️ {f.occupied}/{f.beds}</span>
                  </div>
                  <div className="progress mt8"><div style={{ width: `${f.beds ? Math.round(f.occupied / f.beds * 100) : 0}%` }} /></div>
                  <div className="row spread small mt8">
                    <span style={{ color: C_PAID }}>✅ {rupee(f.collected)}</span>
                    <span style={{ color: f.dueAmount ? C_PENDING : 'var(--muted)' }}>⚠️ {rupee(f.dueAmount)}</span>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* income vs expense */}
          <div className="card mt16">
            <b>📊 {t('incomeVsExpense')}</b>
            <BarChart series={report.series} />
            <div className="row wrap mt8">
              <span className="chip green">■ {t('income')}</span>
              <span className="chip red">■ {t('expenses')}</span>
            </div>
            <div className="mt16">
              {report.series.slice(-1).map(s => (
                <div key={s.month} className="row spread">
                  <span className="muted">{t('netProfit')} · {t('thisMonth')}</span>
                  <b style={{ color: s.profit >= 0 ? 'var(--green2)' : '#c53030', fontSize: 20 }}>{rupee(s.profit)}</b>
                </div>
              ))}
            </div>
          </div>

          {Object.keys(report.expenseByCategory || {}).length > 0 && (
            <div className="card mt16">
              <b>🛒 {t('byCategory')}</b>
              <div className="row wrap mt16">
                {Object.entries(report.expenseByCategory).sort((a, b) => b[1] - a[1]).map(([cat, amt]) => {
                  const ico = EXPENSE_CATS.find(c => c[0] === cat)?.[1] || '📦';
                  return <span key={cat} className="chip orange">{ico} {t(cat)}: {rupee(amt)}</span>;
                })}
              </div>
            </div>
          )}
        </>
      )}

      {modal === 'addExpense' && (
        <AddExpenseModal properties={properties} defaultProp={propId || properties[0]?.id}
          onDone={() => { setModal(null); load(); refreshOverview(); }} onClose={() => setModal(null)} />
      )}
      {sheetTenant && (
        <TenantSheet tenant={sheetTenant}
          onChanged={async () => { load(); refreshOverview(); }}
          onClose={() => setSheetTenant(null)} />
      )}
    </div>
  );
}

/* ============ charts (inline SVG, app theme) ============ */

// ring meter: single ratio, not a 2-slice pie
function OccupancyRing({ rate }) {
  const r = 42, c = 2 * Math.PI * r;
  return (
    <svg width="110" height="110" viewBox="0 0 110 110" role="img" aria-label={`Occupancy ${rate}%`}>
      <circle cx="55" cy="55" r={r} fill="none" stroke="var(--surface2)" strokeWidth="12" />
      <circle cx="55" cy="55" r={r} fill="none" stroke={C_ACCENT} strokeWidth="12" strokeLinecap="round"
        strokeDasharray={`${(rate / 100) * c} ${c}`} transform="rotate(-90 55 55)" />
      <text x="55" y="52" textAnchor="middle" fontSize="22" fontWeight="800" fill="var(--text)">{rate}%</text>
      <text x="55" y="70" textAnchor="middle" fontSize="10" fill="var(--muted)">🛏️</text>
    </svg>
  );
}

// collected vs pending, grouped columns with 2px gaps and value tooltips
function PairBars({ series }) {
  const max = Math.max(1, ...series.flatMap(s => [s.collected, s.pending]));
  return (
    <div className="bar-chart">
      {series.map(s => (
        <div key={s.month} className="bar-group">
          <div className="bar-pair">
            <div className="bar" style={{ height: `${(s.collected / max) * 100}%`, background: C_PAID }} title={`${s.label} · Collected ₹${s.collected.toLocaleString('en-IN')}`} />
            <div className="bar" style={{ height: `${(s.pending / max) * 100}%`, background: C_PENDING }} title={`${s.label} · Pending ₹${s.pending.toLocaleString('en-IN')}`} />
          </div>
          <span className="bar-label">{s.label}</span>
        </div>
      ))}
    </div>
  );
}

function AreaChart({ series }) {
  const W = 320, H = 110, PAD = 6;
  const max = Math.max(1, ...series.map(s => s.amount));
  const pts = series.map((s, i) => [
    PAD + (i / Math.max(1, series.length - 1)) * (W - PAD * 2),
    H - PAD - (s.amount / max) * (H - PAD * 2 - 14)
  ]);
  const line = pts.map((p, i) => `${i ? 'L' : 'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ');
  const area = `${line} L${pts[pts.length - 1][0].toFixed(1)},${H - PAD} L${pts[0][0].toFixed(1)},${H - PAD} Z`;
  const last = series[series.length - 1];
  return (
    <div style={{ overflowX: 'auto' }}>
      <svg width="100%" viewBox={`0 0 ${W} ${H + 16}`} role="img" aria-label="Monthly revenue trend">
        <path d={area} fill={C_ACCENT} opacity="0.12" />
        <path d={line} fill="none" stroke={C_ACCENT} strokeWidth="2" strokeLinejoin="round" />
        {pts.map((p, i) => (
          <circle key={i} cx={p[0]} cy={p[1]} r={i === pts.length - 1 ? 4 : 2.5} fill={C_ACCENT}
            stroke="var(--card)" strokeWidth="2">
            <title>{series[i].label}: ₹{series[i].amount.toLocaleString('en-IN')}</title>
          </circle>
        ))}
        {/* direct label on the latest point only */}
        <text x={pts[pts.length - 1][0]} y={Math.max(10, pts[pts.length - 1][1] - 10)} textAnchor="end" fontSize="11" fontWeight="700" fill="var(--text)">
          ₹{last.amount.toLocaleString('en-IN')}
        </text>
        {series.map((s, i) => (i % 2 === 0 &&
          <text key={s.month} x={pts[i][0]} y={H + 12} textAnchor="middle" fontSize="9" fill="var(--muted)">{s.label}</text>
        ))}
      </svg>
    </div>
  );
}

function BarChart({ series }) {
  const max = Math.max(1, ...series.flatMap(s => [s.income, s.expense]));
  return (
    <div className="bar-chart">
      {series.map(s => (
        <div key={s.month} className="bar-group">
          <div className="bar-pair">
            <div className="bar inc" style={{ height: `${(s.income / max) * 100}%` }} title={`Income ₹${s.income}`} />
            <div className="bar exp" style={{ height: `${(s.expense / max) * 100}%` }} title={`Expense ₹${s.expense}`} />
          </div>
          <span className="bar-label">{s.label}</span>
        </div>
      ))}
    </div>
  );
}

function AddExpenseModal({ properties, defaultProp, onDone, onClose }) {
  const { t } = useLang();
  const toast = useToast();
  const [f, setF] = useState({ propertyId: defaultProp || '', category: 'electricity', amount: '', note: '', date: new Date().toISOString().slice(0, 10) });
  const [busy, setBusy] = useState(false);
  const submit = async (e) => {
    e.preventDefault(); setBusy(true);
    try { await post('/expenses', f); onDone(); }
    catch (err) { toast(err.message, 'err'); setBusy(false); }
  };
  return (
    <Modal title={t('addExpense')} icon="🛒" onClose={onClose}>
      <form onSubmit={submit}>
        <Field label={`🏠 ${t('properties')}`}>
          <select className="input" required value={f.propertyId} onChange={e => setF({ ...f, propertyId: e.target.value })}>
            <option value="" disabled>—</option>
            {properties.map(p => <option key={p.id} value={p.id}>{p.icon} {p.name}</option>)}
          </select>
        </Field>
        <Field label={t('category')}>
          <div className="row wrap">
            {EXPENSE_CATS.map(([v, ico]) => (
              <button type="button" key={v} className={`chip ${f.category === v ? 'active' : ''}`} onClick={() => setF({ ...f, category: v })}>{ico} {t(v)}</button>
            ))}
          </div>
        </Field>
        <div className="row">
          <Field label={`💰 ${t('amount')}`}>
            <input className="input" type="number" min="1" required value={f.amount} onChange={e => setF({ ...f, amount: e.target.value })} />
          </Field>
          <Field label={`📅 ${t('date')}`}>
            <input className="input" type="date" value={f.date} onChange={e => setF({ ...f, date: e.target.value })} />
          </Field>
        </div>
        <Field label={`📝 ${t('note')}`}>
          <input className="input" value={f.note} onChange={e => setF({ ...f, note: e.target.value })} />
        </Field>
        <button className="btn btn-primary btn-block" disabled={busy}>✅ {t('save')}</button>
      </form>
    </Modal>
  );
}
